In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
### nd = n dimentions

In [6]:
np.array([1,2,3,4,5,'abhi','4+7j',])

array(['1', '2', '3', '4', '5', 'abhi', '4+7j'], dtype='<U11')

In [7]:
np.array([1,2,3,4.5])

array([1. , 2. , 3. , 4.5])

In [8]:
np.array([[1,2],[3,4],[5,6]]) ### One d array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
np.array([[1,3],[3,4],[6,7,8]]) ## two d array

C:\Users\ABINAS~1\AppData\Local\Temp/ipykernel_19300/1285483999.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]]) ## two d array


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [10]:
np.array([[[1,3],[3,4]],[[6,7],[9,8]]]) ## 3d array

array([[[1, 3],
        [3, 4]],

       [[6, 7],
        [9, 8]]])

In [11]:
np.array([1,2,3],ndmin = 3)

array([[[1, 2, 3]]])

In [12]:
np.array([1,2,3],ndmin = 30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [13]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [14]:
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [15]:
np.array([1,0,3], dtype = bool)

array([ True, False,  True])

In [16]:
np.array([(1,2) , (4,5)])

array([[1, 2],
       [4, 5]])

In [17]:
np.array([(1,2) , (4,5)], dtype =[("a",'<i2'),("b","<i8")])

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
arr = np.array([(1,2) , (4,5)], dtype =[("a",'<i2'),("b","<i8")])

In [19]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [20]:
arr[0][0]

1

In [21]:
type(arr[0][0])

numpy.int16

In [22]:
arr[0][1]

2

In [23]:
type(arr[0][1])

numpy.int64

In [24]:
arr = np.array([[1,2],[4,5]])

In [25]:
arr

array([[1, 2],
       [4, 5]])

In [26]:
arr[0][1]

2

In [27]:
arr[1][0]

4

In [28]:
type(arr[0][1])

numpy.int32

In [29]:
mat=np.matrix(arr)

In [30]:
l = [3,4,5,6,78]

In [31]:
np.array(l)

array([ 3,  4,  5,  6, 78])

In [32]:
np.asanyarray(l)

array([ 3,  4,  5,  6, 78])

In [33]:
np.asanyarray(mat)

matrix([[1, 2],
        [4, 5]])

In [34]:
np.asarray(mat)

array([[1, 2],
       [4, 5]])

In [35]:
issubclass(np.matrix , np.ndarray) ## Matrix are the subclass

True

In [36]:
issubclass( np.ndarray, np.matrix ) 

False

In [37]:
arr

array([[1, 2],
       [4, 5]])

In [38]:
a = arr

In [39]:
b = np.copy(arr)

In [40]:
arr [0][0] = 76

In [41]:
arr

array([[76,  2],
       [ 4,  5]])

In [42]:
a

array([[76,  2],
       [ 4,  5]])

In [43]:
b

array([[1, 2],
       [4, 5]])

In [44]:
arr[0:10]

array([[76,  2],
       [ 4,  5]])

In [45]:
arr[-1]

array([4, 5])

In [46]:
for i in arr:
    print(i)

[76  2]
[4 5]


In [47]:
for z in arr:
    print(z)

[76  2]
[4 5]


In [48]:
np.fromfunction(lambda i, j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [49]:
type(np.fromfunction(lambda i, j:i==j,(4,4)))

numpy.ndarray

In [50]:
np.fromfunction(lambda i, j:i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [51]:
np.fromfunction(lambda i, j:i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [52]:
np.fromfunction(lambda i, j:i/j,(3,3))

C:\Users\ABINAS~1\AppData\Local\Temp/ipykernel_19300/214633590.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j:i/j,(3,3))
C:\Users\ABINAS~1\AppData\Local\Temp/ipykernel_19300/214633590.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j:i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [53]:
(i*i for i in range(5))

<generator object <genexpr> at 0x00000202E0EA8F20>

In [54]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [55]:
def test(x):
    yield x

In [56]:
test(5)

<generator object test at 0x00000202E0EA8900>

In [57]:
test(5)

<generator object test at 0x00000202E0E6DCF0>

In [58]:
gen = (i*i for i in range(5))

In [59]:
gen

<generator object <genexpr> at 0x00000202E0EC3120>

In [60]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [61]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [62]:
gen
for i in gen:
    print(i)

In [63]:
np.fromstring('1,2,3,4,5,6', sep = ',', dtype = int)

array([1, 2, 3, 4, 5, 6])

In [64]:
np.fromstring("2445 455 565 4543" , sep = " ", dtype = int)

array([2445,  455,  565, 4543])

In [65]:
np.fromstring("2445 455 565 4543" , sep = " ", dtype = complex)

array([2445.+0.j,  455.+0.j,  565.+0.j, 4543.+0.j])

In [66]:
l = [3,4,5,6,7,8]

In [67]:
np.array(l)

array([3, 4, 5, 6, 7, 8])

In [68]:
arr = np.array(l)

# 

In [69]:
arr1 = [[1,2,3,5],[5,6,7,8]]

In [70]:
type(arr1)

list

In [71]:
type(arr)

numpy.ndarray

In [72]:
arr1.ndim


AttributeError: 'list' object has no attribute 'ndim'

In [73]:
arr1 = np.array([[1,2,3,5],[5,6,7,8]])

In [74]:
arr1

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [75]:
type(arr1)

numpy.ndarray

In [76]:
arr1.ndim

2

In [77]:
arr1.size

8

In [78]:
arr1.shape

(2, 4)

In [79]:
arr1.dtype

dtype('int32')

In [80]:
arr

array([3, 4, 5, 6, 7, 8])

In [81]:
arr.size

6

In [82]:
arr.ndim

1

In [83]:
arr.shape

(6,)

In [84]:
arr2 = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [85]:
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [86]:
arr2.size

16

In [87]:
arr2.shape # here two 2 x 4 data

(2, 2, 4)

In [88]:
arr2.ndim

3

In [89]:
arr4 = np.array([[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]]])

In [90]:
arr4

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [91]:
arr4.ndim

4

In [92]:
arr4.shape

(1, 4, 2, 4)

In [93]:
arr4.size

32

In [94]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [95]:
list(range(6.6))

TypeError: 'float' object cannot be interpreted as an integer

In [96]:
np.arange(6.6)## for floating 

array([0., 1., 2., 3., 4., 5., 6.])

In [97]:
np.arange(6.6,9,-.3)

array([], dtype=float64)

In [98]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [99]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
np.linspace(3,8)

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [101]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [102]:
np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [105]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [106]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [108]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [109]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [110]:
np.ones(4)

array([1., 1., 1., 1.])

In [114]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [111]:
np.ones((2,3,1))

array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]])

In [112]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [115]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [116]:
np.empty((3,4))

array([[1.09255211e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 2.67819036e+184, 1.80161618e+185,
        2.12944833e-052],
       [5.85599187e+170, 8.97193892e-067, 5.19997390e-062,
        8.30399095e-067]])

In [119]:
np.eye(3)  ##identity matriex

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.linspace(2,4,4)

array([2.        , 2.66666667, 3.33333333, 4.        ])

In [121]:
np.linspace(2,4,4, endpoint = False)

array([2. , 2.5, 3. , 3.5])

In [123]:
np.linspace(2,4,4, endpoint = False,axis = 0)

array([2. , 2.5, 3. , 3.5])

In [124]:
np.linspace([1,6],4, endpoint = False,axis = 0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [125]:
np.linspace([1,6],4, endpoint = False,axis = 1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [127]:
np.logspace(2,3, 5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [129]:
np.logspace([2,3], 5)

array([[   100.        ,   1000.        ],
       [   115.13953993,   1098.54114199],
       [   132.57113656,   1206.79264064],
       [   152.64179672,   1325.71136559],
       [   175.75106249,   1456.3484775 ],
       [   202.35896477,   1599.85871961],
       [   232.99518105,   1757.51062485],
       [   268.26957953,   1930.69772888],
       [   308.88435965,   2120.95088792],
       [   355.64803062,   2329.95181052],
       [   409.49150624,   2559.5479227 ],
       [   471.48663635,   2811.76869797],
       [   542.86754393,   3088.84359648],
       [   625.05519253,   3393.2217719 ],
       [   719.685673  ,   3727.59372031],
       [   828.64277285,   4094.91506238],
       [   954.09547635,   4498.43266897],
       [  1098.54114199,   4941.71336132],
       [  1264.85521686,   5428.67543932],
       [  1456.3484775 ,   5963.62331659],
       [  1676.83293681,   6551.2855686 ],
       [  1930.69772888,   7196.85673001],
       [  2222.99648253,   7906.04321091],
       [  2

In [131]:
np.logspace([2,3], 5, axis =1)

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [132]:
np.logspace([2],[3], 5, axis = 0)

array([[ 100.        ],
       [ 177.827941  ],
       [ 316.22776602],
       [ 562.34132519],
       [1000.        ]])

In [133]:
d =np.linspace(4,7,40) ## produce 40 data in between 4 to 7

In [134]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [135]:
d.ndim

1

In [136]:
d.shape

(40,)

In [137]:
d.size

40

In [138]:
d.reshape(40,1) ## change the shape of data in 40 x 1

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [139]:
d.reshape(1,2,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [140]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [143]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [144]:
d.reshape(2,2,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [145]:
np.random.rand(3)

array([0.097928  , 0.04407818, 0.09703584])

In [146]:
np.random.randn(5)

array([-0.66898054,  0.17367996,  0.54050403,  0.95687761,  0.49176549])

In [147]:
np.random.rand(2,3)

array([[0.88929759, 0.57486969, 0.54095547],
       [0.34483283, 0.08546589, 0.22286211]])

In [148]:
np.random.rand(2,2,3)

array([[[0.42943118, 0.32310314, 0.1375052 ],
        [0.13945034, 0.03268855, 0.08780078]],

       [[0.3569377 , 0.66023036, 0.35221142],
        [0.58598517, 0.76971453, 0.49142518]]])

In [149]:
np.random.randint(5)

1

In [150]:
np.random.randint(5)

0

In [151]:
np.random.randint(5)

2

In [152]:
np.random.randint(5,6)

5

In [153]:
np.random.randint(5,6)

5

In [158]:
np.random.randint(5,60)

7

In [159]:
np.random.randint(5,60)

57

In [160]:
np.random.randint(5,60)

33

In [161]:
np.random.randint(5,60,(4,4)) ## create 4 x 4 matrix between 5 to 60

array([[21, 56,  6,  6],
       [55, 35,  9, 25],
       [32, 26, 44, 38],
       [31, 41, 22, 59]])

In [163]:
np.random.rand(2,2,3)

array([[[0.83653443, 0.24603449, 0.59304246],
        [0.91937481, 0.52779599, 0.96141502]],

       [[0.92519834, 0.04861218, 0.27939895],
        [0.72191663, 0.05865   , 0.57089588]]])

In [164]:
arr = np.random.randint(3,9,(3,3))

In [165]:
arr

array([[4, 6, 4],
       [7, 6, 4],
       [4, 7, 8]])

In [167]:
arr.reshape(1,9)

array([[4, 6, 4, 7, 6, 4, 4, 7, 8]])

In [168]:
arr.reshape(9,1)

array([[4],
       [6],
       [4],
       [7],
       [6],
       [4],
       [4],
       [7],
       [8]])

In [170]:
arr.reshape(1,1,9)

array([[[4, 6, 4, 7, 6, 4, 4, 7, 8]]])

In [171]:
arr.reshape(1,1,1,9)

array([[[[4, 6, 4, 7, 6, 4, 4, 7, 8]]]])

In [172]:
arr.reshape(1,3,3)

array([[[4, 6, 4],
        [7, 6, 4],
        [4, 7, 8]]])

In [173]:
arr.reshape(3,3,1)

array([[[4],
        [6],
        [4]],

       [[7],
        [6],
        [4]],

       [[4],
        [7],
        [8]]])

In [174]:
arr.reshape(3,-1)

array([[4, 6, 4],
       [7, 6, 4],
       [4, 7, 8]])

In [176]:
arr.reshape(3,3)

array([[4, 6, 4],
       [7, 6, 4],
       [4, 7, 8]])

In [177]:
arr.reshape(1,-1746453)

array([[4, 6, 4, 7, 6, 4, 4, 7, 8]])

In [178]:
arr.max()

8

In [179]:
arr.min()

4

In [182]:
arr = np.random.randint(4,10,(5,5))

In [183]:
arr

array([[5, 8, 4, 4, 6],
       [7, 5, 7, 7, 4],
       [4, 7, 8, 6, 6],
       [4, 4, 8, 4, 6],
       [5, 4, 5, 5, 4]])

In [184]:
arr[3:, 3:]

array([[4, 6],
       [5, 4]])

In [186]:
arr[4:,4:]

array([[4]])

In [187]:
arr[: , [1,3]]

array([[8, 4],
       [5, 7],
       [7, 6],
       [4, 4],
       [4, 5]])

In [188]:
arr[3:, :]

array([[4, 4, 8, 4, 6],
       [5, 4, 5, 5, 4]])

In [189]:
arr

array([[5, 8, 4, 4, 6],
       [7, 5, 7, 7, 4],
       [4, 7, 8, 6, 6],
       [4, 4, 8, 4, 6],
       [5, 4, 5, 5, 4]])

In [190]:
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [191]:
arr<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [192]:
arr[arr<10]

array([5, 8, 4, 4, 6, 7, 5, 7, 7, 4, 4, 7, 8, 6, 6, 4, 4, 8, 4, 6, 5, 4,
       5, 5, 4])

In [193]:
arr[arr>10]

array([], dtype=int32)

In [195]:
arr[arr<10]

array([5, 8, 4, 4, 6, 7, 5, 7, 7, 4, 4, 7, 8, 6, 6, 4, 4, 8, 4, 6, 5, 4,
       5, 5, 4])

In [196]:
arr * arr

array([[25, 64, 16, 16, 36],
       [49, 25, 49, 49, 16],
       [16, 49, 64, 36, 36],
       [16, 16, 64, 16, 36],
       [25, 16, 25, 25, 16]])

In [200]:
arr1 = np.random.randint(2,4,(3,3))

In [201]:
arr2 = np.random.randint(2,4,(3,3))

In [202]:
arr1

array([[2, 3, 2],
       [3, 2, 2],
       [3, 3, 2]])

In [203]:
arr2

array([[2, 3, 2],
       [3, 3, 2],
       [3, 2, 2]])

In [204]:
arr1 * arr2

array([[4, 9, 4],
       [9, 6, 4],
       [9, 6, 4]])

In [205]:
arr1@arr2 ## for matrix multiplication

array([[19, 19, 14],
       [18, 19, 14],
       [21, 22, 16]])

In [206]:
arr **2

array([[25, 64, 16, 16, 36],
       [49, 25, 49, 49, 16],
       [16, 49, 64, 36, 36],
       [16, 16, 64, 16, 36],
       [25, 16, 25, 25, 16]], dtype=int32)

In [207]:
arr/0

C:\Users\ABINAS~1\AppData\Local\Temp/ipykernel_19300/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [209]:
## BroadCasting

arr = np.zeros((3,4))

In [210]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [212]:
a = np.array([1,2,3,4])

In [214]:
a

array([1, 2, 3, 4])

In [213]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [215]:
b = np.array([5,6,7])

In [216]:
b

array([5, 6, 7])

In [217]:
b.reshape(3,1)

array([[5],
       [6],
       [7]])

In [218]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [219]:
b

array([5, 6, 7])

In [221]:
b = np.array([[5,6,7]])

In [223]:
b.T +arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [224]:
arr = np.random.rand(5,4)

In [225]:
arr

array([[0.01610155, 0.34122657, 0.65950883, 0.30664241],
       [0.85413153, 0.41588551, 0.9461643 , 0.70629307],
       [0.04570621, 0.42026769, 0.74730828, 0.18841394],
       [0.2969132 , 0.3212237 , 0.92381158, 0.63341693],
       [0.32181733, 0.43676102, 0.41738484, 0.97745927]])

In [226]:
np.sqrt(arr)

array([[0.12689187, 0.58414602, 0.81210149, 0.55375302],
       [0.92419236, 0.64489186, 0.97270977, 0.84041244],
       [0.2137901 , 0.64828056, 0.86446994, 0.43406674],
       [0.54489743, 0.566766  , 0.96115118, 0.79587495],
       [0.56728945, 0.66087897, 0.64605328, 0.9886654 ]])

In [228]:
np.exp(arr)

array([[1.01623188, 1.40667192, 1.93384226, 1.35885497],
       [2.34933316, 1.51571232, 2.57581066, 2.02646536],
       [1.04676683, 1.52236902, 2.11130931, 1.20733317],
       [1.34569849, 1.37881399, 2.51887301, 1.88403722],
       [1.37963273, 1.54768616, 1.51798659, 2.65769516]])

In [229]:
np.log10(arr)

array([[-1.7931324 , -0.46695715, -0.18077938, -0.51336778],
       [-0.06847525, -0.38102621, -0.02403344, -0.15101505],
       [-1.34002482, -0.376474  , -0.12650021, -0.72488698],
       [-0.52737049, -0.49319242, -0.0344166 , -0.19831033],
       [-0.49239058, -0.35975613, -0.37946332, -0.00990133]])

In [238]:
arr1=np.random.randint(2,5, (5,5))

In [239]:
np.log10(arr1)

array([[0.60205999, 0.47712125, 0.60205999, 0.47712125, 0.30103   ],
       [0.47712125, 0.60205999, 0.60205999, 0.47712125, 0.30103   ],
       [0.47712125, 0.30103   , 0.60205999, 0.47712125, 0.60205999],
       [0.60205999, 0.30103   , 0.47712125, 0.47712125, 0.30103   ],
       [0.60205999, 0.60205999, 0.30103   , 0.30103   , 0.30103   ]])

In [240]:
arr1

array([[4, 3, 4, 3, 2],
       [3, 4, 4, 3, 2],
       [3, 2, 4, 3, 4],
       [4, 2, 3, 3, 2],
       [4, 4, 2, 2, 2]])

In [241]:
np.log(arr1)

array([[1.38629436, 1.09861229, 1.38629436, 1.09861229, 0.69314718],
       [1.09861229, 1.38629436, 1.38629436, 1.09861229, 0.69314718],
       [1.09861229, 0.69314718, 1.38629436, 1.09861229, 1.38629436],
       [1.38629436, 0.69314718, 1.09861229, 1.09861229, 0.69314718],
       [1.38629436, 1.38629436, 0.69314718, 0.69314718, 0.69314718]])

In [242]:
np.random.seed(13)

In [243]:
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [245]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])